version: '3.7'
services:
    redis:
      image: redis:6.0.5
      command: redis-server --requirepass changeme --save 60 1 --port 6379
      container_name: redis6379
      hostname: redis6379
      labels:
        - "name=redis"
        - "mode=standalone"
      ports:
        - 6379:6379
      volumes:
        - ./master/data:/data
